language: python

python:
  - "3.7"

env:
  global:
    - SECRET_KEY=abcdefghijklmnopqrstuvwxyz0123456789
    - DATABASE_URL=sqlite:///db.sqlite3

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python manage.py test -v2 -k
